### ISSUE TITLE
Rage Click Histogram bucket numbers

### ISSUE THREAD

**Issue by nicjansma** [rum-archive/rum-archive#13]
Hi everyone!

One item we've found with our dataset, is the column `RAGECLICKSHISTOGRAM` may have histogram bucket numbers off-by-one from what was intended.

For review, all of the other Timers' [histograms](https://rumarchive.com/docs/methodology/#histogram-bucketing) like PLT, DNS, etc are:

* Bucket 0 should contain values where that timer was 0
* Bucket 1 should contain values for the first high-precision bucket (e.g. 1-100ms for PLT)
* Bucket 2-100 should contain the rest of the high-precision values
* Buckets 101-150 should contain the low-precision values
* Bucket 151 is any data outside of the low-precision range

However for Rage Clicks, which is the only "metric" (a count) we've exported so far, it looks like we have in practice

* Bucket 0 if Rage Clicks were zero (which we skip)
* Bucket 1 is unused
* Bucket 2-100 is if Rage Click count is 1-99
* Bucket 101-150 is Rage Click Count 100-600
* Bucket 151 is >600

I think this is a bug -- Bucket 1 is essentially unused.  We should just use buckets 1-100 for Rage Click counts of 1-100 to simplify things, instead of Buckets 2-100 mapping to clicks of 1-99.

i.e. it looks like our SQL that generates the bucket number is:

        CASE
            WHEN (rageClicks IS NULL OR rageClicks < 0) THEN NULL
            WHEN rageClicks = 0 THEN 0
            WHEN rageClicks <= 100 THEN rageClicks + 1 // this should be just 'rageClicks'?
            WHEN rageClicks <= 600 THEN FLOOR((rageClicks - 100) / 10) + 101
            ELSE 151
        END AS rageClicksBucket,
In the above, we shouldn't be doing `THEN rageClicks + 1`.  Instead we should just have `THEN rageClicks` so bucket 1-100 map to Rage Click count of 1-100 exactly.

I think we have two options:
* Fix this calculation, which means over-time data would differ at a specific date (we'd have to document this, but it could be a pain to use this data over time then)
* Document this oddity in the documentation, and just live with it.

**Comment by rmarx** [comment]
Repeating what I said on the webperf slack:

> I'd say option 1. HTTP archive has plenty instances where stuff changed and so will RUM archive over time. It's also not like there's a huge amount of data in there yet at this point. Handling the edge case also doesn't seem too difficult. 

One thing to consider might be to rename the column to something like `RAGECLICKHISTOGRAMV2` to make the difference explicit. However, I'm not sure this scales too well over time (again, I'm expecting more of this type of thing to show up).

**Comment by bluesmoon** [comment]
I'd just fix it and not worry about the 3 or 4 months where it's off by one. We could technically also fix those months since it's just a bucket shift, but may be work.

**Comment by nicjansma** [comment]
This was fixed with data from March 2023 onward.  Details in https://rumarchive.com/blog/2023-03-16-mpulse-january-data-rage-clicks-change/
