### ISSUE TITLE
Track Safari minor versions

### ISSUE THREAD

**Issue by foolip** [rum-archive/rum-archive#16]
I tried these queries:

```sql
SELECT USERAGENTVERSION, SUM(BEACONS) AS TOTALCOUNT
FROM `akamai-mpulse-rumarchive.rumarchive.rumarchive_page_loads`
WHERE date >= '2023-04-01' and date < '2023-05-01' and USERAGENTFAMILY = 'Safari'
GROUP BY USERAGENTVERSION
ORDER BY TOTALCOUNT
```

and

```sql
SELECT USERAGENTVERSION, SUM(BEACONS) AS TOTALCOUNT
FROM `akamai-mpulse-rumarchive.rumarchive.rumarchive_page_loads`
WHERE date >= '2023-04-01' and date < '2023-05-01' and USERAGENTFAMILY = 'Mobile Safari'
GROUP BY USERAGENTVERSION
ORDER BY TOTALCOUNT
```

In the results, the versions are only whole numbers like 16, 15, 14, etc.

It would be great to include the Safari minor version as well, since they also contain new web platform features. See https://github.com/web-platform-dx/feature-set/issues/173#issuecomment-1555386336 where @othermaciej from the WebKit team explains.

I wanted to use this data in https://github.com/web-platform-dx/feature-set/issues/190.

**Comment by bluesmoon** [comment]
With user agent deprecation, this is unlikely to be available going forward.

**Comment by nicjansma** [comment]
I think Safari is still planning on including the minor version in their `User-Agent` string. At least they are currently doing so in 17.1+.

We could consider adding it!

**Comment by foolip** [comment]
If this is a simple change, it would be great!

**Comment by rmarx** [comment]
We discussed this a couple of weeks ago internally. I'm also a big proponent of this and we're looking into if it's possible to add this (some issues on past vs new data and how to name the versions specifically, but should be solve-able I think :))

**Comment by nicjansma** [comment]
April 2024 dataset onward will include minor versions for Safari and iOS!

Details here:

https://rumarchive.com/blog/2024-05-09-mpulse-april-2024-release-notes-minor-versions/
