### ISSUE TITLE
What do the dates before 2022-09-01 mean? Single day or whole month?

### ISSUE THREAD

**Issue by foolip** [rum-archive/rum-archive#18]
I'm looking at the documentation here:

https://github.com/rum-archive/rum-archive/blob/8ac959be6948642c9a61f8a6eefcfa21452d30c5/src/datasets/index.md?plain=1#L31-L34

When the date is 2021-10-01, for example, does that mean beacons on that very day, the month October, or perhaps the month of September?

**Comment by foolip** [comment]
Trying to answer my own question:

`SELECT SUM(BEACONS) FROM `akamai-mpulse-rumarchive.rumarchive.rumarchive_page_loads` WHERE DATE >= '2022-09-01' and DATE < '2022-10-01';` is 8,183,265,821.

`SELECT SUM(BEACONS) FROM `akamai-mpulse-rumarchive.rumarchive.rumarchive_page_loads` WHERE DATE >= '2022-08-01' and DATE < '2022-09-01';` is 258,795,263.

The first number is 31x times larger than the second, so this probably means previous data is only available one day for every month.  That's good news in  way, it means the `DATE` field means the same thing across the dataset.

**Comment by bluesmoon** [comment]
Right. The data is at "day" granularity.

**Comment by nicjansma** [comment]
@foolip PRs always welcome!  I had tried to convey that aspect through the `(onward, daily), through ...` statement, but extra clarifying the previous dates are for single days would be fine too!

**Comment by nicjansma** [comment]
I clarified this with:
<img width="1017" alt="image" src="https://github.com/rum-archive/rum-archive/assets/1004649/a7387ee9-046e-466c-8d39-46da2e7fecd2">
