### ISSUE TITLE
How is the User-Agent string parsed?

### ISSUE THREAD

**Issue by foolip** [rum-archive/rum-archive#19]
`akamai-mpulse-rumarchive.rumarchive.rumarchive_page_loads` has `DEVICETYPE `, `USERAGENTFAMILY`, `USERAGENTVERSION` and other fields which I think must be parsed from the User-Agent HTTP header.

The details here could matter a lot, so I'm wondering if the methodology is public or can be made public?

In particular, I'd be very interested to learn what can lead to `USERAGENTFAMILY` being Chrome/Edge/Firefox/Safari but `USERAGENTVERSION` being null, and how `DEVICETYPE` is determined.

**Comment by bluesmoon** [comment]
We use the https://github.com/ua-parser project to parse user agent strings.  Things are changing with user agent deprecation though.

**Comment by foolip** [comment]
Thanks @bluesmoon!

Do you use those regexes directly somehow, via https://www.npmjs.com/package/useragent-ng, or somehow else? I'd just like to define a `parseUA()` that I can use to check what `USERAGENTVERSION` will be for various inputs.

For inspiration, https://radar.cloudflare.com/reports/browser-market-share-2022-q4#methodology is pretty good documentation on how Cloudflare does it, even though it boils down to "proprietary parser". cc @bkardell who found that page.
