### ISSUE TITLE
Where does the data come from? How many sites?

### ISSUE THREAD

**Issue by foolip** [rum-archive/rum-archive#20]
https://rumarchive.com/docs/methodology/ is great, but it would be great to know more about the source of the data. The docs say "from one or more websites", but does that mean all users of https://www.akamai.com/products/mpulse-real-user-monitoring, or something else?

This is important to understand how the data might differ from https://gs.statcounter.com/browser-market-share or https://radar.cloudflare.com/adoption-and-usage.

cc @jgraham

**Comment by foolip** [comment]
To quote @jgraham from a chat room:

> how widely is it deployed?, is it GDPR compliant?, does it get blocked by common tracking protection measures?

**Comment by bluesmoon** [comment]
It isn't all users of mPulse RUM.  It's data from the top 100 websites that use mPulse, and each of those is sampled at a different rate to normalize them to approximately the same amount of data per site. I don't believe we can say more than that.

To answer the other questions:
- Yes it is GDPR compliant
- Yes it gets blocked by common blockers

**Comment by foolip** [comment]
Thanks @bluesmoon, that's very helpful!
