### ISSUE TITLE
more details needed

### ISSUE THREAD

**Issue by matti** [rum-archive/rum-archive#3]
Where does this current data come from? Is it coming from https://www.akamai.com/products/mpulse-real-user-monitoring  - the site / documentation is really thin on this.

Please explain more how is the current data collected.

**Comment by nicjansma** [comment]
Hi @matti !

The _Datasets_ section of the documentation lists where each dataset is coming from: https://rumarchive.com/datasets/

In particular, for mPulse: https://rumarchive.com/datasets/#akamai-mpulse-rum

The _Methodology_ section should also describe how the data is collected, aggregated and shared: https://rumarchive.com/docs/methodology/

Please let me know if you need any other specifics

**Comment by nicjansma** [comment]
We can re-open if you have any further questions.
