### ISSUE TITLE
SITE field

### ISSUE THREAD

**Issue by matti** [rum-archive/rum-archive#4]
`SITE` field seems to contain only value `(multiple)` - what is the point of all this data if it's not site specific. What good does this data serve?

**Comment by matti** [comment]
@nicjansma so what's a concrete use case for this data? I opened it in BigQuery and I can't figure out anything sensible out of it.

**Comment by nicjansma** [comment]
The [querying examples](https://rumarchive.com/docs/samples/) give you some sample use-cases for ways of interacting with the data.

With the current data, you can look at it primarily in two ways:

* Marketing analytics, e.g. calculating the relative popularity of particular dimensions (most popular Browser or HTTP Protocol, and how those change over time)
* Performance analytics, e.g. filtering to specific dimensions (e.g. Chrome) and/or grouping by those dimensions (e.g. Country) to see any of the timers (e.g. Page Load Time) and Metrics (e.g. CLS) as a snapshot-in-time or over-time if you're looking at multiple days

**Comment by nicjansma** [comment]
We can re-open if you have any further questions.
